import "./GiveAway.css";
import React from "react";
import closeModal from "../../../assets/closeModal.svg";

const GiveawayModal = ({giveawayModal, setGiveawayModal}) => {
     return (
          <div className={giveawayModal ? 'giveaway-modal show' : 'giveaway-modal hide'}>
          <img src={closeModal} style={{ width: 30, marginBottom: 10, cursor: "pointer" }} onClick={() => setGiveawayModal(false)}></img><br></br>
          {"To celebrate our launch, we will be GIVING AWAY 30% of the revenue generated by the game to the top 3 addresses (17%, 8%, 5%) with the most total bet amount exactly 30 days after the official launch."}
          <br></br><br></br>
          {"We will also GIVE AWAY 20% of the revenue generated to 2 random addresses that play the game at least 5 times"}
          <br></br><br></br>
        </div>
     );
}

export default GiveawayModal;