import { useEffect, useState } from "react";
import "./WelcomeModal.css";
import closeModal from "../../../assets/closeModal.svg";

const WelcomeModal = () => {
	const [welcomeModal, setWelcomeModal] = useState(false);

	useEffect(() => {
		const hasEnteredAlready = localStorage.getItem("hasEnteredAlready");
		if (!hasEnteredAlready) {
			setWelcomeModal(true);
		}
	}, []);

	function handleWelcomeClose() {
		localStorage.setItem("hasEnteredAlready", true);
		setWelcomeModal(false);
	}

	return (
		<div className={welcomeModal ? "welcome-modal show" : "welcome-modal hide"}>
			<img
				src={closeModal}
				style={{ width: 30, marginBottom: 10, cursor: "pointer" }}
				onClick={handleWelcomeClose}
			></img>
			<br></br>
			{"Welcome to Grand Gambit!"}
			<br></br>
			<br></br>
			{
				"To celebrate our launch, we will be GIVING AWAY 30% of the revenue generated by the game to the top 3 addresses (17%, 8%, 5%) with the most total bet amount exactly 30 days after the official launch."
			}
			<br></br>
			<br></br>
			{
				"We will also GIVE AWAY 20% of the revenue generated to 2 random addresses that play the game at least 5 times"
			}
			<br></br>
			<br></br>
			{
				"At the bottom of the website you can see some charts of the current biggest winners, hopefully we see your address there soon!"
			}
		</div>
	);
};

export default WelcomeModal;
